### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by gedw99** [gonutz/wui#1]
This is a really useful library.

I am trying to work out how to access the printer spool on windows. Could not find anything in the W32 lib.

The firm's I just screenshot using the golang lib called robot-vg.

If you know how to access the windows print spooler I can help with some aspects ??

**Comment by gonutz** [comment]
What is it that you want to print? You said you use a screenshot right now so do you want to print a screenshot of the window?

Regarding general printing functions in Go under Windows, this is probably a better fit for the [w32](https://github.com/gonutz/w32) library. We could create Go wrapper functions in there that use the `Winspool.drv` DLL to wrap the functions in the [Print Spooler API Reference](https://docs.microsoft.com/en-us/windows/desktop/printdocs/printing-and-print-spooler-reference).

Maybe you could expand more on the problem at hand that you are trying to solve right now. We can then add the necessary library functions to `w32` and expand on that in the future when new use cases arise.

**Comment by gonutz** [comment]
Since you have not yet responded to this issue and it does not seem to be related to the wui library, I am going to close this for now. Feel free to re-open it or as I said open an issue in the w32 library if you like to.
