### ISSUE TITLE
LinkLabel

### ISSUE THREAD

**Issue by JohnyXXX** [gonutz/wui#10]
Hey, how do i create a `LinkLabel` like this?:
>![LinkLabel](https://user-images.githubusercontent.com/36200531/127847631-73ff60dd-794e-4e12-8f5b-0447f6d79ca4.jpg)

I tried adding `.SetText("<a href=\"https://google.com\">google.com</a>")` for the `TextLabel`, but it didn't work.

**Comment by gonutz** [comment]
Link labels have an extra window style as far as I remember. I have actually looked into what standard controls to support in this library and have decided against link labels. But now that you want one and have a real use case for it, I do consider them. Right now I do not have time to implement that really. If you want to you can give it a shot. Use the Label as a starting point if you like, I will help you out if you post here.

**Comment by JohnyXXX** [comment]
I want to ask for help with this if possible.
My example of a piece of code:
>`label3:=wui.NewLabel()`
`label3.SetBounds(20,205,150,13)`
`label3.SetText("<a href=\"https://link.com\">link</a>")`
`window.Add(label3)`

Can you tell me how to make a `LinkLabel` out of this?
Or how to apply extra window style to `Label`?

**Comment by gonutz** [comment]
What I mean is that you look into the wui library and create a new thing LinkLabel, using Label as an example.
