### ISSUE TITLE
How do I bind a key to NewEditLine object?

### ISSUE THREAD

**Issue by soobakjonmat** [gonutz/wui#12]
Hello I'm a newbie who found out this gui library today.
I have the following example of my code:
```
func main() {
	x := 70
	y := 70
	width := 180
	height := 60

	window := wui.NewWindow()
	window.SetSize(500, 500)
	entry := wui.NewEditLine()
	entry.SetSize(width, height)
	entry.SetPosition(x, y)
	entry.SetText("this is an entry")
	window.Add(entry)
	window.Show()
}
```
I am trying to make a program that when I am 'focused' (like when my text cursor is flashing at the entry) on the entry object, and I press return key, it deletes the entered text, then executes a function.
I tried using SetOnKeyDown and OnKeyDown function but they both don't accept an int variable so I can't figure out how to use it.
Thanks

p.s. This is just my opinion, but I think it would be very helpful for newbies if you can add a bit more code to 'Minimal Example' section in README. Like few basic examples of label, button and editLine like my example code.

**Comment by gonutz** [comment]
Hey, thanks for checking out the library! :-)

First of all, you are right, there should be more examples. The reason there are none is that this library is still in development, although not currently, as I do not have much time on my hands right now.

The edit line does not have events for key presses. Instead you can use a shortcut on the return key and ask the entry if it has focus. Add this code right before you call `window.Show()`:

```
	window.SetShortcut(func() {
		if entry.HasFocus() {
			entry.SetText("")
		}
	}, wui.KeyReturn)
```

**Comment by gonutz** [comment]
Side note, if you want nicer looking text in your app, try this:

```
	font, _ := wui.NewFont(wui.FontDesc{Name: "Tahoma", Height: -13})
	window.SetFont(font)
```

**Comment by soobakjonmat** [comment]
Thank you very much! And if you want, I could write a few basic (like really basic) example codes in README. Would you accept the pull request if I did that?

**Comment by gonutz** [comment]
Thanks for the offer but I am still working out the API. Once I get back around to working on `wui` I might even add a `v3`. I do not want you to waste your time but of course I see the value of having working examples for the status quo.

So if you are using `wui` anyway and in the learning process can create some examples that would have helped you, those will surely be very useful to others, too. I would be happy to include good examples in the repo.
