### ISSUE TITLE
Are background colors and text colors for labels and buttons not yet supported?

### ISSUE THREAD

**Issue by soobakjonmat** [gonutz/wui#13]
Are background colors and text colors for labels and buttons not yet supported?

**Comment by gonutz** [comment]
That is correct, labels have no settable color yet.
If you really need this, you can use a PaintBox, whose Canvas has the function `TextOut(x, y int, s string, color Color)`.

**Comment by gonutz** [comment]
The plan is of course to allow you to color all your UI elements the way you want but for now I had not had the need to do it, that is why it is not yet implemented.

**Comment by soobakjonmat** [comment]
Okay thank you

**Comment by soobakjonmat** [comment]
I'm sorry to bother you again, but I could not figure out the way to use the PaintBox color thing that you have mentioned. Could you please tell me how to use it? Or if it's easier for you, you can just give me a simple example.
Thank you.

**Comment by gonutz** [comment]
Sure, there you go:

```
package main

import "github.com/gonutz/wui/v2"

func main() {
	font, _ := wui.NewFont(wui.FontDesc{Name: "Tahoma", Height: -13})

	window := wui.NewWindow()
	window.SetTitle("Paint Boxes for Colored Labels")
	window.SetFont(font)

	left := wui.NewPaintBox()
	left.SetBounds(10, 10, 120, 25)
	window.Add(left)
	left.SetOnPaint(func(c *wui.Canvas) {
		width, height := c.Size()
		c.FillRect(0, 0, width, height, wui.RGB(255, 128, 128))
		const text = "light red"
		_, textH := c.TextExtent(text)
		c.TextOut(5, (height-textH)/2, text, wui.RGB(0, 0, 0))
	})

	center := wui.NewPaintBox()
	center.SetBounds(10, 50, 120, 25)
	window.Add(center)
	center.SetOnPaint(func(c *wui.Canvas) {
		width, height := c.Size()
		c.FillRect(0, 0, width, height, wui.RGB(128, 255, 128))
		const text = "light green"
		textW, textH := c.TextExtent(text)
		c.TextOut((width-textW)/2, (height-textH)/2, text, wui.RGB(0, 0, 0))
	})

	window.Show()
}
```

**Comment by soobakjonmat** [comment]
Thank you very much again!

**Comment by gonutz** [comment]
No problem :-)

**Comment by soobakjonmat** [comment]
Sorry I got another another problem... but I believe this will be the last one (hopefully).
So I wrote these functions:
```
func changePaintBoxProperty(paintBox *wui.PaintBox, text string, textColor *wui.Color) {
	window.Remove(paintBox)
	paintBox.SetOnPaint(func(c *wui.Canvas) {
		width, height := paintBox.Size()
		textW, textH := c.TextExtent(text)
		c.TextOut((width-textW)/2, (height-textH)/2, text, *textColor)
	})
	window.Add(paintBox)
	time.Sleep(500 * time.Millisecond)
}

func createNewPaintBox(text string, xPos int, yPos int, width int, height int, textColor *wui.Color, font *wui.Font) *wui.PaintBox {
	newPaintBox := wui.NewPaintBox()
	newPaintBox.SetBounds(xPos, yPos, width, height)
	newPaintBox.SetOnPaint(func(c *wui.Canvas) {
		width, height := newPaintBox.Size()
		c.SetFont(font)
		textW, textH := c.TextExtent(text)
		c.FillRect(0, 0, width, height, BG_COLOR_RGB)
		c.TextOut((width-textW)/2, (height-textH)/2, text, *textColor)
	})
	window.Add(newPaintBox)
	return newPaintBox
}

func main() {
	window = wui.NewWindow()
	window.SetTitle("Test app")
	window.SetSize(260, 140)


	testPaintBox = createNewPaintBox(.............)
	go changePaintBoxProperty()

	window.Show()
}

```

And I'm using changePaintBoxProperty() with goroutine to update the text and color of multiple PaintBox objects with interval of 0.5 seconds.
The problem is, this line `window.Remove(paintBox)` in changePaintBoxProperty() function doesn't seem to work in this situation. I know this because after executing my app, I can see that the PaintBox objects that are getting overlapped. And after a while, my app gets laggy and freezes (possibly because of too much objects are added on window). Can you see what I'm doing wrong? Or do you think you have a better way of doing this?

**Comment by soobakjonmat** [comment]
Never mind, I used `fmt.Println(len(window.Children()))` and figured out that the remove function works so I guess there is something else which is causing this issue. Sorry for bothering once again.

**Comment by gonutz** [comment]
I am not really sure what you want to achieve. Do you just want to update the color of the paint box label? In that case, just use a global variable and call PaintBox.Paint() which will repaint the thing, then using the new color.

**Comment by gonutz** [comment]
Also, you do not bother me at all, no need to apologize :-)
