### ISSUE TITLE
How to draw image after some event

### ISSUE THREAD

**Issue by bogus43** [gonutz/wui#17]
Hi again :),
How to draw image on paintBox after other event, for example OnButtonClick? I wrote code like below, but it is not working. 
In below code I want to draw png image on PaintBox after clicking "Show Image" button.

**Comment by bogus43** [comment]
package main

import (
	"bytes"
	"image/png"
	"os"

	"github.com/gonutz/wui/v2"
)

func main() {
	windowFont, _ := wui.NewFont(wui.FontDesc{
		Name:   "Tahoma",
		Height: -11,
	})

	window := wui.NewWindow()
	window.SetFont(windowFont)
	window.SetInnerSize(371, 276)
	window.SetTitle("Window")

	paintBox1 := wui.NewPaintBox()
	paintBox1.SetBounds(10, 9, 329, 204)
	window.Add(paintBox1)

	button1 := wui.NewButton()
	button1.SetBounds(128, 223, 85, 25)
	button1.SetText("Show Image")
	window.Add(button1)

	button1.SetOnClick(func() {
		data, _ := os.ReadFile("aztec.png")
		img, _ := png.Decode(bytes.NewReader(data))
		wuiImage := wui.NewImage(img)

		paintBox1.SetOnPaint(func(c *wui.Canvas) {
			c.FillRect(0, 0, c.Width(), c.Height(), wui.RGB(255, 0, 255))
			c.DrawImage(wuiImage, wuiImage.Bounds(), 0, 0)
		})
	})

	window.Show()
}

**Comment by gonutz** [comment]
You generally want to set the events once in the setup code. It can reference an image variable which you can change in your event. Then you call `paintBox1.Paint()` which is the way to trigger a repaint event. This will call the OnPaint event that you have set earlier. Also, the event is triggered when you resize your window for example, Windows will determine when a window needs repainting, for example after you wake up your computer after a sleep, when the window is resized or when the Windows theme is changed. This means you get some paint events automatically and to force a repaint you use `PaintBox.Paint()`.

**Comment by bogus43** [comment]
Ok generally I added only paintBox1.Paint() to this code and now it working fine for me. Thanks :) 

```
paintBox1.SetOnPaint(func(c *wui.Canvas) {
			c.FillRect(0, 0, c.Width(), c.Height(), wui.RGB(255, 0, 255))
			c.DrawImage(wuiImage, wuiImage.Bounds(), 0, 0)
		})
		paintBox1.Paint()
	})

	window.Show()
```

**Comment by gonutz** [comment]
Great, always happy to help out :-)
