### ISSUE TITLE
why this module doesn't display docs on pkg.go.dev

### ISSUE THREAD

**Issue by jba** [gonutz/wui#2]
This is a response to the feedback filed today on pkg.go.dev.

We look for semver tags on the repo and use those to decide which version to display by default. For this repo, v2.0.0 is the latest tag, and https://github.com/gonutz/wui/tree/v2.0.0 does not contain a license file. Nor does v1.0.0. 

If you tag master and "go get" it with that tag via the proxy, it should work.

**Comment by gonutz** [comment]
Oh OK, thanks for the quick response! I will tag a new version when I get around to it. My other libraries need an overhaul as well for playing nice with versioning.

What do you mean by 

> "go get" it with that tag via the proxy, it should work.

Do you mean I have to specify the version in the URL of your page?

**Comment by jba** [comment]
If you haven't changed the GOPROXY environment variable, then any time you run `go get` and it has doesn't find the module locally, it will download it from the proxy (https://proxy.golang.org). So after you push the tag (say it's v2.1.0 for the sake of argument), you'd just have to run
```
go get github.com/gonutz/wui@v2.1.0
```
That will make the proxy aware of it.  pkg.go.dev will then notice, and process your module at the new version.

**Comment by gonutz** [comment]
How can a web site be affected by something I do locally on my machine, like set some proxy for `go get`? I am not trolling here, I just think this sounds too complicated. I like the way godoc.org updates itself from the latest github repo and that is it. Simple and usable. Unfortunately [it tells me it cannot find wui anymore](https://godoc.org/?q=github.com%2Fgonutz%2Fwui) for some reason. It pointed me at pkg.go.dev but that is not a replacement for it it seems.

**Comment by jba** [comment]
We're working on a simpler flow, where you'll be able to click something on pkg.go.dev to fetch the latest version of your module.

Most of the time, things will just work: whenever someone anywhere in the world gets the latest version of your module, it will show up soon after on pkg.go.dev.

I don't understand why godoc.org isn't showing your package any more. We haven't changed it except to put that yellow banner at the top.

**Comment by gonutz** [comment]
That would be a great addition, the Refresh button from godoc.org. Still the licensing thing bothers me. Why do I have to add a license to everything now for pkg.go.dev but for godoc.org it is not necessary? This hinders usability as well.

You say most of the time things will just work but actually this sounds like most of the time the opposite is true. Roughly 100% (rounded to the nearest integer) of repositories on Github are only used by one person, the author. There is no need for the author to `go get` their own repositories usually. That means MOST of the repos do not show up as the most current version on pkg.go.dev. This would only be true for popular repos.

I understand that you work on godoc.org as well? In that case I would ask you if it is possible to fix the problem there? I have been using godoc.org as long as I use Go itself and it is always the first thing I open for a new library I find. Until very recently it showed my wui library without a problem. I don't know what happened but when I last visited it, the yellow banner was not there. Whatever other changes were applied along with that might have caused the problem.

**Comment by gonutz** [comment]
OK, thanks for your help, it seems someone else go got this library, the v2.1.0 is now displayed on pkg.go.dev. Still the process is not quite user-friendly so I am happy that you guys are working on it :-)
