### ISSUE TITLE
Set Minimum and Maximum Size?

### ISSUE THREAD

**Issue by lthon09** [gonutz/wui#25]
Is there a way to set the minimum or maximum size of the window? I don't see any option to. Thanks!

**Comment by gonutz** [comment]
Have you found a way to do it? You closed the issue again.

**Comment by lthon09** [comment]
Unfortunately no, I just gave up hhh

**Comment by gonutz** [comment]
Oh OK, you could maybe try settings the Window's size in the OnResize event. I don't know if that works though, just a thought. In other news, I only need a couple more decades before releasing version 3 which now that you mentioned the issue, will have a way to have control over the window size :-)
