### ISSUE TITLE
Treetable 

### ISSUE THREAD

**Issue by ddkwork** [gonutz/wui#26]
Can you make a treetable widget like this?

https://githubfast.com/richardwilkes/unison/blob/main/table_model.go#L34-L44

has some features as:
Sort coluwn
Set row color
N tree as set parent etc

"github.com/richardwilkes/unison" and
github.com/richardwilkes/gcs
 
![image](https://github.com/gonutz/wui/assets/19886504/628070db-e36e-4a30-ab01-1cd40f7e8e66)

![image](https://github.com/gonutz/wui/assets/19886504/1923e028-49f3-46a7-b66a-117d89b4157d)

**Comment by gonutz** [comment]
Quick reply without looking further into it: the lib as is does not offer a tree widget. I doubt that the Windows API provides anything like this out of the box.

You can however use a `PaintBox` and draw everything yourself ;-)

On a more serious note, I am not working much on this library at the moment and will probably not do so for the foreseeable future.
