### ISSUE TITLE
Unable to build: w32.* undefined

### ISSUE THREAD

**Issue by Merith-TK** [gonutz/wui#5]
using the same example found in the readme

```
$ go build
# github.com/gonutz/wui
C:\Users\zachd\go\pkg\mod\github.com\gonutz\wui@v2.1.0+incompatible\menu.go:72:15: undefined: w32.MIIM_STATE
C:\Users\zachd\go\pkg\mod\github.com\gonutz\wui@v2.1.0+incompatible\menu.go:74:17: undefined: w32.MFS_CHECKED
C:\Users\zachd\go\pkg\mod\github.com\gonutz\wui@v2.1.0+incompatible\menu.go:76:17: undefined: w32.MFS_UNCHECKED
C:\Users\zachd\go\pkg\mod\github.com\gonutz\wui@v2.1.0+incompatible\menu.go:90:15: undefined: w32.MIIM_STRING
C:\Users\zachd\go\pkg\mod\github.com\gonutz\wui@v2.1.0+incompatible\paintbox.go:312:25: undefined: w32.AC_SRC_ALPHA
```

**Comment by gonutz** [comment]
Please update the [w32 library](https://github.com/gonutz/w32), for example the `AC_SRC_ALPHA` is defined [here](https://github.com/gonutz/w32/blob/5e5fd7c0d69552b77531b3595f15a9d54454a437/constants.go#L3189). Seems your code is out of date. Note also that I do not use Go modules. Instead I only depend on my own libraries and keep everything in sync so if you use the latests versions of all my libraries, you are fine.

**Comment by Merith-TK** [comment]
this is after making sure all of the deps were up to date...

I would suggest using go modules so that the dependencies are automatically pulled

**Comment by Merith-TK** [comment]
Okay so it works without being in a go-module, but breaks when not... why?

**Comment by gonutz** [comment]
OK, I now vendor w32, which is the only dependency. This way the wui repo is fully self-contained, no problems should arise if you just use the latest wui version.

**Comment by thegtproject** [comment]
I need help because this is driving me insane. I get the same exact problem this issue was opened with. I've tried redownloading/reinstalling/cleaning cache and cleaning modcache. But, still go insists on pulling some version of w32 without the needed constants.

```C:\dev\projects\rampage>go build .\cmd\rampage 
# github.com/gonutz/wui
C:\Users\thegt\go\pkg\mod\github.com\gonutz\wui@v2.2.0+incompatible\menu.go:72:15: undefined: w32.MIIM_STATE
C:\Users\thegt\go\pkg\mod\github.com\gonutz\wui@v2.2.0+incompatible\menu.go:74:17: undefined: w32.MFS_CHECKED
C:\Users\thegt\go\pkg\mod\github.com\gonutz\wui@v2.2.0+incompatible\menu.go:76:17: undefined: w32.MFS_UNCHECKED
C:\Users\thegt\go\pkg\mod\github.com\gonutz\wui@v2.2.0+incompatible\menu.go:90:15: undefined: w32.MIIM_STRING
C:\Users\thegt\go\pkg\mod\github.com\gonutz\wui@v2.2.0+incompatible\paintbox.go:312:25: undefined: w32.AC_SRC_ALPHA       
C:\Users\thegt\go\pkg\mod\github.com\gonutz\wui@v2.2.0+incompatible\window.go:813:8: undefined: w32.UnregisterClassAtom```
