### ISSUE TITLE
How to run designer

### ISSUE THREAD

**Issue by aidar666** [gonutz/wui#7]
Hey, can`t run designer by using "go run designer.go", getting error like "...\designer.go:2037:13: undefined: generateProperties,  how do I do that? Sorry for bothering

**Comment by aidar666** [comment]
I realised a minute after I wrote that, sorry

**Comment by gonutz** [comment]
I just recently brought the designer back up to work with Go modules. Go modules make life really hard, that is why I have not worked with Go much lately. But right now, the latest version online will be able to run the preview with Ctrl+R.
The designer is not finished, it can be used to layout widgets and generate code from that. The plan was to make it read code files back in, parse the code and let you edit it visually. I do not know whether that is ever going to happen but I still use the wui framework from time to time for little tools I write.

Let me know what you do with this thing, I am always happy to hear from users of my projects :-)
